steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
        ".",
      ]

  # Step 2: Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
      ]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
        "--region",
        "$_REGION",
        "--platform",
        "managed",
        "--memory",
        "512Mi",
        "--cpu",
        "1",
        "--min-instances",
        "0",
        "--max-instances",
        "10",
        "--port",
        "8080",
        "--allow-unauthenticated",
      ]

# Use substitutions so you don't have to hardcode names
substitutions:
  _SERVICE_NAME: chracl-rating-dashboard
  _REGION: asia-northeast1
  _REPO_NAME: nextjs

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
